- service: notify.mobile_app_mi_9_lite
    data:
      title: Whirlpool
      message: Whirlpool is ON
  mode: single
- id: 'xxxxx'
  alias: Push-Notify/Whirlpool Heater ON
  description: ''
  trigger:
  - platform: state
    entity_id: switch.intex_heater
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_mi_9_lite
    data:
      title: Whirlpool heater
      message: The heater is ON!
  mode: single
- id: 'xxxxxxx'
  alias: Push-Notify/Whirlpool Set. Temp >33째C
  description: ''
  trigger:
  - platform: mqtt
    topic: IntexSpa/Temperature Setpoint
    payload: '33'
  condition: []
  action:
  - service: notify.mobile_app_mi_9_lite
    data:
      title: Whirlpool Set. Temp
      message: The setpoint temperature is over 33째C
  mode: single
- id: 'xxxxxxx'
  alias: Push-Notify/Whirlpool Actual Temperature >34째C
  description: ''
  trigger:
  - platform: mqtt
    topic: IntexSpa/Actual Temperature
    payload: '34'
  condition: []
  action:
  - service: notify.mobile_app_mi_9_lite
    data:
      title: Whirlpool Actual Temperature
      message: The actual temperature is over 34째C
  mode: single
- id: 'xxxxxxxx'
  alias: Push-Notify/Whirlpool Error Message
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.status
    above: '0'
  condition: []
  action:
  - service: notify.mobile_app_mi_9_lite
    data:
      title: Whirlpool Error
      message: ATTENTION! Whirlpool Error {{ states('sensor.status') }}
  mode: single
