---------------------------- Only whirlpool config -------------------------
#Switch MQTT
switch
  - platform mqtt
    command_topic IntexSpaCmd Power on off
    state_topic IntexSpaPower on
    payload_on 1
    payload_off 0
    name Intex_ON
    
  - platform mqtt
    command_topic IntexSpaCmd water filter on off
    state_topic IntexSpafilter on
    payload_on 1
    payload_off 0
    name Intex_Filter
    
  - platform mqtt
    command_topic IntexSpaCmd bubble on off
    state_topic IntexSpaBubble on
    payload_on 1
    payload_off 0
    name Intex_Bubble
    
  - platform mqtt
    command_topic IntexSpaCmd heater on off
    state_topic IntexSpaheater on
    payload_on 1
    payload_off 0
    name Intex_heater
    
  - platform mqtt
    command_topic IntexSpaCmd decrease
    state_topic IntexSpaCmd decrease
    payload_on 1
    payload_off 0
    name Intex_decrease-
    
  - platform mqtt
    command_topic IntexSpaCmd increase
    state_topic IntexSpaCmd increase
    payload_on 1
    payload_off 0
    name Intex_increase+
    
  - platform mqtt
    command_topic IntexSpaCmd water jet on off
    state_topic IntexSpaWater jet on
    payload_on 1
    payload_off 0
    name Intex_Water Jet
    
  - platform mqtt
    command_topic IntexSpaCmd sanizer on off
    state_topic IntexSpaSanizer on
    payload_on 1
    payload_off 0
    name Intex_Sanizer
    
  - platform mqtt
    command_topic IntexSpaCmd Reset ESP
    state_topic IntexSpaCmd Reset ESP
    payload_on reset
    payload_off  
    name Reset ESP-script-switch

#Sensor
sensor
  - platform mqtt
    name Status
    state_topic IntexSpaError Number
    unit_of_measurement 'E'
  - platform mqtt
    name Aktuelle Temp.
    state_topic IntexSpaActual Temperature
    unit_of_measurement '°c'
  - platform mqtt
    name Set Temp.
    state_topic IntexSpaTemperature Setpoint
    unit_of_measurement '°c'
  - platform mqtt
    name IntexSpa_Communication with pump
    state_topic IntexSpaCommunication with pump
    
#Template Sensor   
  - platform template
    sensors
      intexstatustemplate
        friendly_name Intex Status Template
        value_template -
          {% if is_state('sensor.status','0') %}
            OK
          {% else %}
            E 
            {{ states('sensor.status') }}
          {% endif %}
  - platform template
    sensors
      intexkommunikationmitpumpetemplate
        friendly_name Communication with pump - Template
        value_template -
          {% if is_state('sensor.intexspa_communication_with_pump','1') %}
            OK
          {% else %}
            Keine Verbindung
-------------------------